global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      # NanoPi R76S (RK3576)
      - targets: ['100.80.80.80:9100']
        labels:
          instance: 'NanoPi-R76S(RK3576)'
      
      # NanoPi M6 (RK3588)
      - targets: ['100.90.90.90:9100']
        labels:
          instance: 'NanoPi-M6(RK3588)'
      
      # Middle server for RK3588
      - targets: ['10.10.10.107:9100']
        labels:
          instance: 'Middle-server(RK3576)'

      # Middle server for RK3588
      - targets: ['10.10.10.103:9100']
        labels:
          instance: 'Middle-server(RK3588)'
